export enum TradebookID {
    GapGiveAndGoBookmapReversal = 'GapGiveAndGoBookmapReversal',
    GapAndGoBookmapOfferWallBreakout = 'GapAndGoBookmapOfferWallBreakout',
    GapDownAndGoDownBookmapBidWallBreakdown = 'GapDownAndGoDownBookmapBidWallBreakdown',
    GapAndCrapBookmapBidWallBreakdown = 'GapAndCrapBookmapBidWallBreakdown',
    GapAndCrapBookmapReversal = 'GapGapAndCrapBookmapReversal',
    GapDownAndGoUpBookmapOfferWallBreakout = 'GapDownAndGoUpBookmapOfferWallBreakout',
    GapGiveAndGoLong = 'GapGiveAndGoLong',
    ATHVwapCont = 'ATHVwapCont',
    BookmapBigWallBreakdownFailLong = 'BookmapBigWallBreakdownFailLong',
    VwapContinuationLong = 'VwapContinuationLong',
    VwapContinuationShort = 'VwapContinuationShort',
    OpenDriveLong = 'openDriveLong',
    OpenDriveShort = 'openDriveShort',
    LongVwapPushdownFailed = 'LongVwapPushdownFailed',
    ShortVwapBounceFailed = 'ShortVwapBounceFailed',
    GapAndCrapShortVwapBounceFailed = 'GapAndCrap-ShortVwapBounceFailed',
    GapDownAndGoDownShortVwapBounceFailed = 'GapDownAndGoDown-ShortVwapBounceFailed',
}
