export enum TradebookID {
    GapAndGoBookmapOfferWallBreakout = 'GapAndGoBookmapOfferWallBreakout',
    GapDownAndGoDownBookmapBidWallBreakdown = 'GapDownAndGoDownBookmapBidWallBreakdown',
    GapAndCrapBookmapBidWallBreakdown = 'GapAndCrapBookmapBidWallBreakdown',
    GapAndCrapBookmapRejection = 'GapAndCrapBookmapRejection',
    GapAndCrapShort = 'GapAndCrapShort',
    GapDownAndGoDownShort = 'GapDownAndGoDownShort',
    GapDownAndGoUpBookmapOfferWallBreakout = 'GapDownAndGoUpBookmapOfferWallBreakout',
    GapGiveAndGoLong = 'GapGiveAndGoLong',
    ATHVwapCont = 'ATHVwapCont',
    BookmapBigWallBreakdownFailLong = 'BookmapBigWallBreakdownFailLong',
    VwapContinuationLong = 'VwapContinuationLong',
    VwapContinuationShort = 'VwapContinuationShort',
    OpenDriveLong = 'openDriveLong',
    OpenDriveShort = 'openDriveShort',
    LongVwapPushdownFailed = 'LongVwapPushdownFailed',
    ShortVwapBounceFailed = 'ShortVwapBounceFailed',
    GapAndCrapShortVwapBounceFailed = 'GapAndCrap-ShortVwapBounceFailed',
    GapDownAndGoDownShortVwapBounceFailed = 'GapDownAndGoDown-ShortVwapBounceFailed',
}
