export const advancedLevelOneQuoteFeaturesEnabled: boolean = false;
export const losthostWithPort: string = "http://localhost:3000";
export const batchCount: number = 10;
export const marketDataSource: string = "massive"; // alpaca, massive
export const impliedMarketCapThresholdInBillions: number = 0.9;
export const competeForTimeAndSales: boolean = true;
export const allowLiveStats: boolean = true;
export const enableLeftPaneFeatures: boolean = true;
export const enableAiAgent: boolean = enableLeftPaneFeatures && true;
export const showBestPlans: boolean = enableLeftPaneFeatures && true;
export const showTradebooksForPosition: boolean = enableLeftPaneFeatures && true;
export const showDataFeedsBar: boolean = false;
export const checkMaxEntryThreshold: boolean = false;
export const tradesPerSecondRollingWindowSeconds: number = 10; // Rolling window for tracking average trades per second